---
- name: Create today local directory
  hosts: CISCO
  gather_facts: no
  connection: local
  tasks:
    - name: timestamp
      local_action: command date +%Y%m%d
      register: timestamp

    - name: create local directory
      file:
        path: /etc/ansible/backups/{{ timestamp.stdout }}
        state: directory
        mode: 0755 

- name: Save Configurations (IOS)
  hosts: CISCO
  gather_facts: no
  ignore_errors: yes
  vars:
    creds:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      auth_pass: switch
  tasks:
    - name: timestamp
      local_action: command date +%Y%m%d
      register: timestamp

    - ios_command:
        provider: "{{ creds }}"
        commands: show run
      register: show_run_ios

#    - debug:
#        msg: "{{ show_run_ios.stdout[0] }}"
    - copy:
        content: "{{ show_run_ios.stdout[0] }}"
        dest: "/etc/ansible/backups/{{ timestamp.stdout }}/{{ inventory_hostname }}_{{ timestamp.stdout }}.txt"